SELECT DISTINCT 
-- SELECIONANDO A TABELA DE ACESSOS
TACESSOS.user_id AS [ID_USUARIO],
TACESSOS.user_name AS [NOME],
TACESSOS.type AS [TIPO DE ACESSO],

TCOMPRAS.ID AS [ID_COMPRA],
TCOMPRAS.price AS [PREÇO COMPRA]

FROM Acessos AS TACESSOS
INNER JOIN Usuarios AS TUSUARIOS ON TUSUARIOS.ID = TACESSOS.user_id
INNER JOIN Compras AS TCOMPRAS ON TUSUARIOS.ID = TCOMPRAS.user_id