SELECT * 
FROM Usuarios

SELECT *
FROM Compras

SELECT DISTINCT
TACESSOS.user_id,
TACESSOS.user_name,
TCOMPRAS.user_id,
TCOMPRAS.price

FROM ACESSOS AS TACESSOS
LEFT JOIN COMPRAS AS TCOMPRAS ON TACESSOS.user_id = TCOMPRAS.user_id
-- LEFT JOIN PRIORIZA O QUE ESTÁ NA TABELA A ESQUERDA.
WHERE TCOMPRAS.user_id IS NULL