SELECT DISTINCT
TUSUARIOS.user_name AS [NOME CADASTRADO],
TUSUARIOS.ID AS [ID CADASTRADO],
TCOMPRAS.user_id AS [ID DE COMPRA],
TACESSOS.user_id AS [ID DE ACESSO]

FROM Usuarios AS TUSUARIOS
FULL JOIN Compras AS TCOMPRAS
ON TUSUARIOS.ID = TCOMPRAS.user_id
FULL JOIN Acessos AS TACESSOS
ON TUSUARIOS.id = TACESSOS.user_id
-- TRAZENDO TODOS OS DADOS
-- FULL JOIN TRAZ TUDO O QUE ESTIVER NA SELEÇÃO EM TODAS AS TABELAS.

--TRAZENDO QUEM NÃO TEM COMPRA OU ACESSO E APENAS CADASTRO NA BASE
SELECT DISTINCT
TUSUARIOS.user_name AS [NOME CADASTRADO],
TUSUARIOS.ID AS [ID CADASTRADO],
TCOMPRAS.user_id AS [ID DE COMPRA],
TACESSOS.user_id AS [ID DE ACESSO]

FROM Usuarios AS TUSUARIOS
FULL JOIN Compras AS TCOMPRAS
ON TUSUARIOS.ID = TCOMPRAS.user_id
FULL JOIN Acessos AS TACESSOS
ON TUSUARIOS.id = TACESSOS.user_id
WHERE TCOMPRAS.user_id IS NULL AND TACESSOS.user_id IS NULL