-- TRANSLATE - SUBSTITUÍ CARACTERES (MAIS DE 1 POR CRITÉRIO)
-- REPLACE - SUBSTITUÍ CARACTERES (SOMENTE 1 POR REPLACE)

SELECT TOP 5
FirstName,
TRANSLATE(FirstName, 'J''E''C', 'T''U''X') AS [TRANSLATE],
REPLACE(REPLACE(FirstName, 'J', 'W'), 'E', 'A') AS [REPLACE]

FROM DimCustomer