-- LTRIM (ELIMINA ESPAÇOS VAZIOS NA ESQUERDA)
-- RTRIM (ELIMINA ESPAÇOS VAZIOS NA DIREITA)
-- RETIRA OS ESPAÇOS VAZIOS NA SELEÇÃO

SELECT 
-- LTRIM - ELIMINANDO ESPAÇO À ESQUERDA
'        TESTE DE ESPAÇO' AS [À ESQUERDA],
LTRIM('        TESTE DE ESPAÇO' ) AS [CORREÇÃO ESQUERDA],

-- LTRIM - ELIMINANDO ESPAÇO À DIREITA
'TESTE DE ESPAÇO        ' AS [À DIREITA],
RTRIM('TESTE DE ESPAÇO        ') AS [CORREÇÃO DIREITA],

'        TESTE DE ESPAÇO        ' AS [CENTRO],
LTRIM(RTRIM('        TESTE DE ESPAÇO        ')) AS [CORREÇÃO AO CENTRO]