-- UPPER (LETRAS MAIÚSCULAS)
-- LOWER (LETRAS MINÚSCULAS)

SELECT
UPPER(FirstName) AS [NOME MAIÚSCULO],
LOWER(FirstName) AS [NOME MINÚSCULO],
UPPER(LastName) AS [SOBRENOME MAIÚSCULO],
LOWER(LastName) AS [SOBRENOME MINÚSCULO]

FROM DimEmployee