SELECT * FROM VENDAS
SELECT * FROM PRODUTO
SELECT * FROM CATEGORIA

--ADICIONANDO CONSTRAINT
--REFERENCIANDO CHAVE ESTRANGEIRA DE PRODUTO
ALTER TABLE VENDAS
	ADD CONSTRAINT FK_PRODUTO FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUTO(ID)

-- APAGANDO CONSTRAINT (APAGANDO CHAVE ESTRANGEIRA)
ALTER TABLE VENDAS
	DROP CONSTRAINT FK_PRODUTO

ALTER TABLE PRODUTO
	ADD CONSTRAINT FK_CATEGORIA FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIA(ID)

-- APAGANDO CONSTRAINT (APAGANDO CHAVE ESTRANGEIRA)
ALTER TABLE PRODUTO
	DROP CONSTRAINT FK_CATEGORIA