-- QUANTIDADE DE VENDAS POR ANO ACIMA DE 3 MIL
-- QUANTIDADE DE VENDAS POR ANO ABAIXO DE 3 MIL

SELECT 
YEAR (ORDERDATE) ANO,
COUNT(CASE WHEN ExtendedAmount < 3000 THEN 1 END) AS [VENDA_BAIXA],
COUNT(CASE WHEN ExtendedAmount >= 3000 THEN 1 END) AS [VENDA_ALTA]

FROM FactResellerSales
GROUP BY YEAR(ORDERDATE)

-- ******************************************************************
-- QUANTIDADE DE VENDAS POR MÊS ACIMA DE 3 MIL
-- QUANTIDADE DE VENDAS POR MÊS ABAIXO DE 3 MIL

SELECT MONTH(ORDERDATE) AS [MÊS],
COUNT(CASE WHEN ExtendedAmount < 3000 THEN 1 END) AS [VENDA BAIXA],
COUNT(CASE WHEN ExtendedAmount >= 3000 THEN 1 END) AS [VENDA ALTA]

FROM FactResellerSales
WHERE YEAR(ORDERDATE) = 2011
GROUP BY MONTH(ORDERDATE)
ORDER BY 1