-- REPLICATE (REPETE O QUE FOR SELECIONADO)
-- REVERSE (INVERTE A PALAVRA DO FINAL PARA O INÍCIO)

-- REPETINDO A LETRA A 20x
SELECT 
REPLICATE('A', 200) AS [LETRA A]

SELECT
REVERSE('PARALELEPIPEDO') AS REVERTENDO