-- ESPELHANDO TABELA TEMPORARIA NO BANCO DE TESTE E DEPOIS ACESSANDO O BANCO DE DADOS ECOMMERCE PARA ACESSAR OUTRA TABELA

SELECT * FROM VENDAS

USE TESTE
SELECT * FROM PRODUTO

SELECT * 
INTO ##TMP_PRODUTO
FROM PRODUTO

SELECT * 
FROM ##TMP_PRODUTO

SELECT
TBVENDAS.ID,
TBVENDAS.PRODUCT_ID,
TBPRODUTO.ID,
TBPRODUTO.NOME_PRODUTO
FROM VENDAS AS TBVENDAS
LEFT JOIN ##TMP_PRODUTO AS TBPRODUTO
ON TBVENDAS.PRODUCT_ID = TBPRODUTO.ID