SELECT *
INTO [CATEGORIA AULA]
FROM CATEGORIA
-- TABELA ESPELHO CRIADA ACIMA

DROP TABLE [CATEGORIA AULA]

SELECT *
INTO [CATEGORIA_ID]
FROM CATEGORIA
WHERE ID IN(0, 1, 2, 3)

SELECT *
FROM CATEGORIA_ID

DROP TABLE CATEGORIA_ID