-- SELECIONANDO BANCO DWADVENTURE
USE DWAdventure

-- SELECIONANDO FACTRESSELERSALES
SELECT *
FROM FactResellerSales

-- SELECIONANDO COM RESTRIÇÕES E CRIANDO TABLE TEMP
SELECT
EmployeeKey,
ProductKey,
ExtendedAmount

INTO ##TEMP_AULA

FROM FactResellerSales
WHERE EmployeeKey = 285

-- SELECIONANDO TABLE TEMP
SELECT *
FROM ##TEMP_AULA

-- USANDO OUTRO BANCO DE DADOS O BANCO TEMPORÁRIO
USE TESTE

SELECT *
INTO DADOS_TESTE
FROM ##TEMP_AULA

-- DADOS TESTE DE OUTRO BANCO NO BANCO TESTE
SELECT *
FROM DADOS_TESTE

