USE TESTE

SELECT *
FROM CATEGORIA

-- ALTERANDO TABELA E ADICIONANDO A COLUNA DE SUBCATEGORIA
ALTER TABLE CATEGORIA
ADD SUBCATEGORIA INT

-- A COLUNA DE SUBCATEGORIA ESTÁ ERRADA, ALTEREI PARA VARCHAR
ALTER TABLE CATEGORIA
ALTER COLUMN SUBCATEGORIA VARCHAR(50)

-- VENDO COLUNAS E TIPOS DE DADOS
EXEC sp_columns CATEGORIA

-- APAGANDO COLUNA DE SUBCATEGORIA
ALTER TABLE CATEGORIA
DROP COLUMN SUBCATEGORIA



