USE DWAdventure

SELECT *
FROM DimEmployee

SELECT *
INTO TB_TEMP_EMPLOYEE
FROM DimEmployee

SELECT *
FROM TB_TEMP_EMPLOYEE

SELECT
	EmployeeKey,
	FirstName,
	LastName,
	MiddleName,
	StartDate,
	EndDate
FROM TB_TEMP_EMPLOYEE

-- ATUALIZANDO DADOS SEM INDICAR AS LINHAS, ACABOU ALTERANDO TODA A COLUNA
UPDATE TB_TEMP_EMPLOYEE
SET EndDate = GETDATE()

-- APAGANDO A TABELA TEMPORÁRIA ... DEPOIS GERO ELA NOVAMENTE PELO COMANDO ACIMA
DROP TABLE TB_TEMP_EMPLOYEE

-- SELECIONANDO FUNCIONÁRIOS ATIVOS COM BASE NA COLUNA ENDDATE
SELECT
	EmployeeKey,
	FirstName,
	LastName,
	MiddleName,
	StartDate,
	EndDate,
	CASE WHEN EndDate IS NULL
	THEN 'ATIVO' ELSE 'DEMITIDO' END AS [STATUS]
FROM TB_TEMP_EMPLOYEE

-- DEMITINDO FUNCIONÁRIOS
UPDATE TB_TEMP_EMPLOYEE
SET EndDate = '2024-11-10'
WHERE EmployeeKey IN(1,2,3)

-- FILTRANDO MIDDLENAME 3, 4, 5 QUANDO NULO JUNTO AO END DATE
SELECT
	EmployeeKey,
	FirstName,
	LastName,
	MiddleName,
	StartDate,
	EndDate,
	CASE WHEN EndDate IS NULL
	THEN 'ATIVO' ELSE 'DEMITIDO' END AS [STATUS]
FROM TB_TEMP_EMPLOYEE
WHERE EmployeeKey IN(3,4,5)
AND MiddleName IS NULL
AND EndDate IS NULL

-- ALTERANDO MIDDLENAME QUANDO NULO JUNTO AO ENDDATE
UPDATE TB_TEMP_EMPLOYEE
SET MiddleName = 'R'
WHERE EmployeeKey IN (3, 4, 5)
AND MiddleName IS NULL
AND EndDate IS NULL

-- DEMITINDO FUNCIONÁRIOS COM BETWEEN (ENTRE 100 E 120)
UPDATE TB_TEMP_EMPLOYEE
SET EndDate = GETDATE()
WHERE EmployeeKey BETWEEN 100 AND 120

-- SELECIONANDO PARA VER RESULTADOS
SELECT
	EmployeeKey,
	FirstName,
	LastName,
	MiddleName,
	StartDate,
	EndDate,
	CASE WHEN EndDate IS NULL
	THEN 'ATIVO' ELSE 'DEMITIDO' END AS [STATUS]
FROM TB_TEMP_EMPLOYEE
WHERE EmployeeKey BETWEEN 100 AND 120

USE DWAdventure
DROP TABLE TB_TEMP_EMPLOYEE