USE DWAdventure

SELECT *
FROM DimEmployee

SELECT *
INTO TB_TEMP_EMPLOYEE
FROM DimEmployee

SELECT *
FROM TB_TEMP_EMPLOYEE

SELECT
	EmployeeKey,
	FirstName,
	LastName,
	MiddleName,
	StartDate,
	EndDate
FROM TB_TEMP_EMPLOYEE

-- ATUALIZANDO DADOS SEM INDICAR AS LINHAS, ACABOU ALTERANDO TODA A COLUNA
UPDATE TB_TEMP_EMPLOYEE
SET EndDate = GETDATE()

-- APAGANDO A TABELA TEMPORÁRIA ... DEPOIS GERO ELA NOVAMENTE PELO COMANDO ACIMA
DROP TABLE TB_TEMP_EMPLOYEE

--
