-- TABELA TEMPORÁRIA PARA NÃO ESTRAGAR A TABELA EXISTENTE
SELECT *
INTO TBTEMP
FROM CATEGORIA

SELECT *
FROM TBTEMP

-- ATUALIZANDO TABELA SEM PASSAR OS PARÂMETROS CORRETOS, BASICAMENTE SUBSTITUI TODAS AS LINHAS DESTA COLUNA
UPDATE TBTEMP
SET NOME_CATEGORIA = 'BESTEIRA'

-- TIVE QUE APAGAR A TABELA
DROP TABLE TBTEMP

-- ATUALIZANDO PASSANDO AS LINHAS QUE DESEJO REALIZAR ALTERAÇÃO
UPDATE TBTEMP
SET NOME_CATEGORIA = 'MODA'
WHERE ID IN(0, 1, 2, 3)

UPDATE TBTEMP
SET NOME_CATEGORIA = 'ESPORTE'
WHERE ID IN(4, 5, 6)