-- DELETE
USE DWAdventure

SELECT *
INTO TB_TEMP_EMPLOYEE
FROM DimEmployee

-- SELECIONANDO COLUNAS ESPECÍFICAS
SELECT
	EmployeeKey,
	FirstName,
	LastName,
	MiddleName,
	StartDate,
	EndDate,
	CASE WHEN EndDate IS NULL THEN 'ATIVO' ELSE 'DEMITIDO' END AS [STATUS],
	DATEDIFF(YEAR, StartDate, GETDATE()) AS [ANOS DE EMPRESA],
	DATEDIFF(MONTH, StartDate, GETDATE()) AS [MESES DE EMPRESA]
FROM TB_TEMP_EMPLOYEE
ORDER BY StartDate

DELETE FROM TB_TEMP_EMPLOYEE
WHERE DATEDIFF(YEAR, StartDate, GETDATE()) = 14
AND EndDate IS NULL

-- EXCLUINDO QUEM JÁ FOI DEMITIDO
DELETE FROM TB_TEMP_EMPLOYEE
WHERE EndDate IS NOT NULL

-- DELETANDO DADOS DE 14/07/2008 ATÉ  07/09/2010
DELETE FROM TB_TEMP_EMPLOYEE
WHERE StartDate BETWEEN '2008-07-14' AND '2010-09-07'

