-- RANK E DENSE RANK
-- RANK() OVER (ORDER BY) AS APELIDO 
-- DENSE_RANK() OVER (ORDER BY) AS APELIDO
-- ROW_NUMBER() OVER (ORDER BY) AS APELIDO -- CONTA LINHAS NÚMERO DAS LINHAS.

USE DWAdventure

--RANK (REPETE O RANKING)
SELECT 
EmployeeKey,
Title AS CARGO,
HireDate [DATA CONTRATAÇÃO],
RANK() OVER (ORDER BY HireDate) AS RANKING
FROM DimEmployee

-- DENSERANK (REPETE O RANKING MAS CONTINUA CONTANDO) // PASSANDO O PARÂMETRO DO ID OU KEY É POSSÍVEL RANKEAR
SELECT 
EmployeeKey,
Title AS CARGO,
HireDate [DATA CONTRATAÇÃO],
DENSE_RANK() OVER (ORDER BY HireDate, EmployeeKey) AS RANKING
FROM DimEmployee

-- ROW_NUMBER() -- CONTA LINHAS NÚMERO DAS LINHAS.
SELECT 
EmployeeKey,
Title AS CARGO,
HireDate [DATA CONTRATAÇÃO],
ROW_NUMBER() OVER (ORDER BY HireDate) AS CONTANDO_LINHAS
FROM DimEmployee

