/* SUB QUERY -- CONSULTA DENTRO DE OUTRA CONSULTA -- 
BASICAMENTE ABRE UMA NOVA SELEÇÃO PARA REALIZAR UMA CONSULTA EM CIMA DE OUTRA CONSULTA */

SELECT * FROM(
SELECT 
EmployeeKey,
Title AS CARGO,
HireDate [DATA CONTRATAÇÃO],
DENSE_RANK() OVER (ORDER BY HireDate, EmployeeKey) AS RANKING
FROM DimEmployee
) AS DADOS_SUBQUERY
WHERE RANKING BETWEEN 1 AND 10