/* SUB QUERY -- CONSULTA DENTRO DE OUTRA CONSULTA -- 
BASICAMENTE ABRE UMA NOVA SELEÇÃO PARA REALIZAR UMA CONSULTA EM CIMA DE OUTRA CONSULTA */

-- SUBQUERY
SELECT * FROM(
SELECT 
EmployeeKey,
Title AS CARGO,
HireDate [DATA CONTRATAÇÃO],
DENSE_RANK() OVER (ORDER BY HireDate, EmployeeKey) AS RANKING
FROM DimEmployee
) AS DADOS_SUBQUERY
WHERE RANKING BETWEEN 1 AND 10

-- TABELA TEMPORÁRIA
SELECT 
EmployeeKey,
Title AS CARGO,
HireDate [DATA CONTRATAÇÃO],
DENSE_RANK() OVER (ORDER BY HireDate, EmployeeKey) AS RANKING
INTO ##TMP_POSICIONANDO_FUNC
FROM DimEmployee

-- SELECIONANDO TB TEMPORÁRIA
SELECT * 
FROM ##TMP_POSICIONANDO_FUNC
WHERE RANKING BETWEEN 1 AND 20

-- AULA 072
-- SELECIONANDO OS VENDEDORES QUE MAIS VENDEM
SELECT 
	EmployeeKey,
	SUM(SalesAmount) AS VENDA,
	DENSE_RANK() OVER(ORDER BY SUM(SalesAmount) DESC) AS [POSIÇÃO]
FROM FactResellerSales
GROUP BY EmployeeKey
ORDER BY SUM(SalesAmount) DESC

-- SELECIONANDO OS VENDEDORES QUE MAIS VENDEM E TRAZENDO DADOS SELECIONADOS POR MEIO DA SUBQUERY
SELECT *
FROM(
	SELECT 
		EmployeeKey,
		SUM(SalesAmount) AS VENDA,
		DENSE_RANK() OVER(ORDER BY SUM(SalesAmount) DESC) AS POSICAO
	FROM FactResellerSales
	GROUP BY EmployeeKey
) AS TB_SUBQUERY_VENDAS

WHERE POSICAO BETWEEN 1 AND 10

-- SELECIONANDO OS VENDEDORES QUE MAIS VENDEM E TRAZENDO DADOS SELECIONADOS POR MEIO DA TABELA TEMPORÁRIA
SELECT 
	EmployeeKey,
	SUM(SalesAmount) AS VENDA,
	DENSE_RANK() OVER(ORDER BY SUM(SalesAmount) DESC) AS POSICAO
	INTO ##TMP_MAIORES_VENDEDORES
FROM FactResellerSales
GROUP BY EmployeeKey

-- SELECIONANDO DADOS DA TABELA TEMPORÁRIA
SELECT *
FROM ##TMP_MAIORES_VENDEDORES
WHERE POSICAO BETWEEN 1 AND 5