-- RANK + SUB QUERY + TAB TEMPORÁRIA
-- POR COLABORADOR O RANKING DE VENDAS POR PRODUTO
USE DWAdventure

-- DO MAIOR PARA O MENOR VALOR
-- PARTITION BY RANKEIA VENDAS, DEPOIS MOSTRA OS COLABORADORES RANKEADOS
SELECT 
	EmployeeKey,
	ProductKey,
	SUM(SalesAmount) AS VENDA,
	DENSE_RANK() OVER(PARTITION BY EmployeeKey ORDER BY SUM(SalesAmount) DESC) AS POSICAO
FROM FactResellerSales
GROUP BY EmployeeKey, ProductKey

-- SUB QUERY COM O MAIOR VALOR DE VENDA (PRODUTO MAIS CARO VENDIDO)
SELECT *
FROM (
	SELECT 
		EmployeeKey,
		ProductKey,
		SUM(SalesAmount) AS VENDA,
		DENSE_RANK() OVER(PARTITION BY EmployeeKey ORDER BY SUM(SalesAmount) DESC) AS POSICAO
	FROM FactResellerSales
	GROUP BY EmployeeKey, ProductKey
) AS PRODUTO_MAISCARO_PORVENDEDOR

WHERE POSICAO = 1

-- SUB QUERY COM O MENOR VALOR DE VENDA (PRODUTO MAIS BARATO VENDIDO)

SELECT *
FROM (
	SELECT 
		EmployeeKey,
		ProductKey,
		SUM(SalesAmount) AS VENDA,
		DENSE_RANK() OVER(PARTITION BY EmployeeKey ORDER BY SUM(SalesAmount)) AS POSICAO
	FROM FactResellerSales
	GROUP BY EmployeeKey, ProductKey
) AS PRODUTO_MAISCARO_PORVENDEDOR

-- TB TEMP DE 1 A 10 POR VENDEDOR
SELECT 
	EmployeeKey,
	ProductKey,
	SUM(SalesAmount) AS VENDA,
	DENSE_RANK() OVER(PARTITION BY EmployeeKey ORDER BY SUM(SalesAmount) DESC) AS POSICAO
	INTO ##TMP_PRODUTO_VENDA
FROM FactResellerSales
GROUP BY EmployeeKey, ProductKey

SELECT *
FROM ##TMP_PRODUTO_VENDA
WHERE POSICAO BETWEEN 1 AND 10