-- AULA 075

SELECT
	-- TABELA DE VENDAS
	TB_VENDAS.EmployeeKey AS [ID_VENDEDOR],
	TB_VENDAS.ProductKey AS [ID_PRODUTO],
	SUM(TB_VENDAS.SalesAmount) AS SOMA_VENDAS,

	-- TABELA DE VENDEDOR
	TB_VENDEDOR.FirstName AS [NOME],
	TB_VENDEDOR.Title AS [CARGO],

	-- TABELA DE PRODUTOS
	TB_PRODUTOS.EnglishProductName AS [PRODUTO],

	-- RANKING POR TOP 10.
	DENSE_RANK() OVER(PARTITION BY TB_VENDAS.EmployeeKey ORDER BY SUM(TB_VENDAS.SalesAmount) DESC) AS RANKING

FROM FactResellerSales AS TB_VENDAS
LEFT JOIN DimEmployee AS TB_VENDEDOR ON TB_VENDAS.EmployeeKey = TB_VENDEDOR.EmployeeKey
LEFT JOIN DimProduct AS TB_PRODUTOS ON TB_VENDAS.ProductKey = TB_PRODUTOS.ProductKey
GROUP BY
    TB_VENDAS.EmployeeKey,
    TB_VENDAS.ProductKey,
    TB_VENDEDOR.FirstName,
    TB_VENDEDOR.Title,
    TB_PRODUTOS.EnglishProductName;

-- SUBQUERY PARA TRAZER DADOS FILTRADOS

SELECT *
FROM (
	SELECT
		-- TABELA DE VENDAS
		TB_VENDAS.EmployeeKey AS [ID_VENDEDOR],
		TB_VENDAS.ProductKey AS [ID_PRODUTO],
		SUM(TB_VENDAS.SalesAmount) AS SOMA_VENDAS,

		-- TABELA DE VENDEDOR
		TB_VENDEDOR.FirstName AS [NOME],
		TB_VENDEDOR.Title AS [CARGO],

		-- TABELA DE PRODUTOS
		TB_PRODUTOS.EnglishProductName AS [PRODUTO],

		-- RANKING POR TOP 10.
		DENSE_RANK() OVER(PARTITION BY TB_VENDAS.EmployeeKey ORDER BY SUM(TB_VENDAS.SalesAmount) DESC) AS RANKING

	FROM FactResellerSales AS TB_VENDAS
	LEFT JOIN DimEmployee AS TB_VENDEDOR ON TB_VENDAS.EmployeeKey = TB_VENDEDOR.EmployeeKey
	LEFT JOIN DimProduct AS TB_PRODUTOS ON TB_VENDAS.ProductKey = TB_PRODUTOS.ProductKey
	GROUP BY
		TB_VENDAS.EmployeeKey,
		TB_VENDAS.ProductKey,
		TB_VENDEDOR.FirstName,
		TB_VENDEDOR.Title,
		TB_PRODUTOS.EnglishProductName
) AS TB_RELATORIO_FILTRADO
WHERE RANKING BETWEEN 1 AND 10