-- TRANSAÇÕES

-- BEGIN TRAN - INICIA A TRANSAÇÃO
-- ROLLBACK TRAN - CANCELAR A TRANSAÇÃO
-- COMMIT TRAN - SALVAR A TRANSAÇÃO

-- SELECIONANDO BANCO PARA USAR
USE TESTE

-- SELECIONANDO TABELA PRODUTO
SELECT *
FROM PRODUTO

-- DELETANDO PRODUTO
DELETE PRODUTO
WHERE ID = 2

SELECT * 
FROM PRODUTO
WHERE ID = 2

-- OS DADOS PRECISAM DE SEGURANÇA, E POR ESSE MOTIVO É NECESSÁRIO REALIZAR TRANSAÇÕES
SELECT *
FROM PRODUTO
WHERE ID IN(1,3,4,5,6,14)

BEGIN TRAN -- INICIA TRANSAÇÃO
ROLLBACK TRAN -- CANCELA TRANSAÇÃO

DELETE PRODUTO
WHERE ID IN(1,3,4,5,6,14)

ALTER TABLE VENDAS
DROP CONSTRAINT FK_PRODUTO;

SELECT *
FROM PRODUTO
WHERE ID IN(15, 16, 17, 20)

DELETE PRODUTO

COMMIT TRAN -- SALVANDO TRANSAÇÃO

-- INSERTS - INSERINDO DADOS
SELECT *
FROM PRODUTO

SELECT *
FROM CATEGORIA

BEGIN TRAN

-- INSERINDO DADOS MANUALMENTE
INSERT INTO PRODUTO(ID, NOME_PRODUTO, CATEGORY_ID)
	VALUES(50, 'CAMISA APERTADA', 0)

-- DELETANDO
DELETE PRODUTO WHERE ID = 50

ROLLBACK TRAN
COMMIT TRAN

-- UPDATE 
SELECT *
FROM PRODUTO
WHERE CATEGORY_ID = 0

-- SIMULANDO ERROS 
SELECT * 
FROM PRODUTO
WHERE ID = 2

UPDATE PRODUTO
	SET NOME_PRODUTO = 'Calça',
	CATEGORY_ID = 1
	WHERE ID = 2
GO

-- USANDO TRANSAÇÕES PARA GARANTIR A INTEGRIDADE DO BANCO DE DADOS.
SELECT *
FROM PRODUTO

BEGIN TRAN -- INICIANDO A TRANSAÇÃO
UPDATE PRODUTO
	SET NOME_PRODUTO = 'CALÇA APERTADA',
	CATEGORY_ID = 1
WHERE ID = 2

ROLLBACK TRAN
COMMIT TRAN