USE Ecommerce

SELECT * FROM Categoria
-- CRIANDO CHAVES PRIMÁRIAS
ALTER TABLE Clientes
ADD CONSTRAINT PK_Clientes PRIMARY KEY (id);

ALTER TABLE Ordens
ADD CONSTRAINT PK_ORDENS PRIMARY KEY (id);

ALTER TABLE Categoria
ADD CONSTRAINT PK_CATEGORIA PRIMARY KEY (id);

ALTER TABLE PRODUTO
ADD CONSTRAINT PK_PRODUTO PRIMARY KEY (id);

ALTER TABLE VENDAS
ADD CONSTRAINT PK_VENDAS PRIMARY KEY (id);

-- RELAÇÃO DE ORDENS -> CLIENTES
ALTER TABLE Ordens
ADD CONSTRAINT FK_Ordens_Clientes
FOREIGN KEY (customer_id) REFERENCES Clientes(id);
-- FOI NECESSÁRIO MUDAR O TIPO DE DADO DE CUSTOMER_ID NA TB_ORDENS
ALTER TABLE ORDENS
ALTER COLUMN CUSTOMER_ID INT NOT NULL;

-- RELAÇÃO DE VENDAS -> ORDENS
ALTER TABLE VENDAS
ADD CONSTRAINT FK_Vendas_Ordens
FOREIGN KEY (order_id) REFERENCES Ordens(id);

ALTER TABLE VENDAS
ALTER COLUMN ORDER_ID INT NOT NULL;

-- RELAÇÃO DE VENDAS -> PRODUTOS
ALTER TABLE Vendas
ADD CONSTRAINT FK_Vendas_Produto
FOREIGN KEY (product_id) REFERENCES Produto(id);

ALTER TABLE VENDAS
ALTER COLUMN PRODUCT_ID INT NOT NULL;

-- RELAÇÃO DE PRODUTOS -> CATEGORIA
ALTER TABLE Produto
ADD CONSTRAINT FK_Produto_Categoria
FOREIGN KEY (category_id) REFERENCES Categoria(id);

ALTER TABLE PRODUTO
ALTER COLUMN CATEGORY_ID INT NOT NULL;




-- JUNÇÕES PARA CRIAÇÃO DE VIEWS
CREATE VIEW VW_PENDENCIA_ENTREGAS AS
SELECT
TB_VENDAS.ID AS [ID_VENDAS],
TB_VENDAS.TOTAL_PRICE AS [PRECO_TOTAL],
TB_VENDAS.QUANTITY AS [QUANTIDADE],

TB_ORDENS.CREATED_AT AS [DATA],
TB_ORDENS.STATUS AS [STATUS],

TB_PRODUTOS.NAME AS [NOME_PRODUTO],

TB_CATEGORIAS.NAME AS [CATEGORIA],

TB_CLIENTES.FIRST_NAME AS [NOME_CLIENTE],
TB_CLIENTES.CELL_PHONE AS [CELULAR],
TB_CLIENTES.STATE AS [ESTADO]

FROM Vendas AS TB_VENDAS
LEFT JOIN Ordens AS TB_ORDENS ON TB_VENDAS.order_id = TB_ORDENS.ID
LEFT JOIN Produto AS TB_PRODUTOS ON TB_VENDAS.product_id = TB_PRODUTOS.ID
LEFT JOIN Categoria AS TB_CATEGORIAS ON TB_PRODUTOS.category_id = TB_CATEGORIAS.ID
LEFT JOIN Clientes AS TB_CLIENTES ON TB_ORDENS.customer_id = TB_CLIENTES.ID
WHERE TB_ORDENS.status = 'entrega_pendente'

SELECT *
FROM VW_PENDENCIA_ENTREGAS
WHERE CATEGORIA = 'Informática' AND ESTADO = 'Distrito Federal'

