-- DATAS

SELECT SYSDATETIME() AS [HORA COMPUTADOR]
SELECT SYSDATETIMEOFFSET() AS [HORA COM FUSO HORÁRIO]
SELECT SYSUTCDATETIME() AS [ELIMINA FUSO HORÁRIO E TRAZ O HORÁRIO DO MARCO ZERO]

SELECT CURRENT_TIMESTAMP
SELECT GETDATE() AS [DATA E HORA DE HOJE]
SELECT GETUTCDATE()

-- FORMATO DE TEXTO
SELECT DATENAME(WEEKDAY, GETDATE()) AS [DIA DA SEMANA]
SELECT DATENAME(YEAR, GETDATE()) AS [ANO]

-- FORMATO INTEIRO
SELECT YEAR(GETDATE()) AS ANO

-- PARTE DA DATA
SELECT DATEPART(YEAR, /*NOME DA COLUNA QUE EXTRAI A DATA*/ GETDATE()) AS ANO
SELECT DATEPART(MONTH, /*NOME DA COLUNA QUE EXTRAI A DATA*/ GETDATE()) AS [MÊS EM NÚMERO]
SELECT DATEPART(DAY, /*NOME DA COLUNA QUE EXTRAI A DATA*/ GETDATE()) AS [DIA EM NÚMERO]
SELECT DATEPART(HOUR, /*NOME DA COLUNA QUE EXTRAI A DATA*/ GETDATE()) AS HORAS
SELECT DATEPART(MINUTE, /*NOME DA COLUNA QUE EXTRAI A DATA*/ GETDATE()) AS MINUTOS
SELECT DATEPART(SECOND, /*NOME DA COLUNA QUE EXTRAI A DATA*/ GETDATE()) AS SEGUNDOS
SELECT DATEPART(MILLISECOND, /*NOME DA COLUNA QUE EXTRAI A DATA*/ GETDATE()) AS MILLISEGUNDOS