USE Ecommerce

SELECT *,
DATENAME(YEAR, created_at) AS ANO,
DATENAME(MONTH, created_at) AS MES,
DATENAME(DAY, created_at) AS DIA
FROM ORDENS

-- RELATÓRIO QUANTIDADE DE VENDAS POR ANO E MÊS
SELECT
DATENAME(YEAR, created_at) AS ANO,
DATENAME(MONTH, created_at) AS MES,
COUNT(ID) AS [QUANTIDADE VENDAS]
FROM ORDENS
GROUP BY DATENAME(YEAR, created_at), DATENAME(MONTH, created_at)
ORDER BY 1,3