USE Ecommerce

SELECT *
FROM Ordens

-- RELATÓRIO DE FORMATO INTEIRO - AS VENDAS DE JANEIRO DE 2019
SELECT 
    COUNT(ID) AS QUANTIDADE_VENDIDA_DIA,
    YEAR(CREATED_AT) AS ANO,
    MONTH(CREATED_AT) AS MES,
    DATEPART(DAY, CREATED_AT) AS DIA
FROM Ordens
-- FILTRANDO POR ANO E MÊS
WHERE YEAR(CREATED_AT) = 2019 AND MONTH(CREATED_AT) = 1
-- AGRUPE POR
GROUP BY YEAR(CREATED_AT), MONTH(CREATED_AT), DATEPART(DAY, CREATED_AT);
