-- SINTAXE
-- DATEADD(INTERVALO(PODE SER ANO, MES, DIA.., QUANTIDADE EM NUMERO INTEIRO (PODE SER 1 ANO, 1 MES, 2 ANOS, 2 MESES) E EXPRESSÃO
-- A EXPRESSÃO PODE SER UMA COLUNA, A DATA ATUAL.


SELECT DATEADD(MONTH, 1, GETDATE()) AS UM_MES_DEPOIS

SELECT DATEADD(YEAR, 2, GETDATE()) AS DOIS_ANOS_DEPOIS

-- DATEADD E CASTING
SELECT DATEADD(MONTH, -1, GETDATE()) AS VOLTANDO_UM_MES

SELECT DATEADD(MONTH, -1, CAST(GETDATE() as DATE)) AS VOLTANDO_UM_MES_COM_CASTING

SELECT CONVERT(VARCHAR, DATEADD(YEAR, 2, GETDATE()), 103) DOIS_ANOS_DEPOIS_FORMATO_DATABR

USE Ecommerce

SELECT *
FROM Ordens


-- RELATÓRIO QUE TRAZ DATA DA VENDA E DATA DE RECEBIMENTO, EXEMPLO PODE SER USADO PARA CARTÕES DE CRÉDITO
SELECT
ID,
CONVERT(VARCHAR, CREATED_AT, 103) AS DATA_VENDAS,
CONVERT(VARCHAR, DATEADD(MONTH, 2, CREATED_AT), 103) AS DATA_PAGAMENTO
FROM Ordens
