-- DATEDIFF(INTERVALO (PODE SER EM ANO, MES, DIA, HORAS..), DATAINICIAL 2024, DATAFINAL 2025)
-- A FUNÇÃO DATEDIFF SUBTRAI A DIFERENÇA ENTRE AS DATAS.

USE DWAdventure

-- DESCOBRINDO O TEMPO DE CASA DOS FUNCIONÁRIOS
SELECT *
FROM DimEmployee

-- SELECIONANDO OS FUNCIONARIOS DEMITIDOS E DESCOBRINDO QUANTO TEMPO ESTIVERAM NA EMPRESA
SELECT 
EmployeeKey,
FirstName,
HireDate,
EndDate
FROM DimEmployee
WHERE EndDate IS NOT NULL

-- FUNCIONÁRIOS DEMITIDOS ACIMA, ABAIXO OS QUE FORAM DEMITIDOS E O TEMPO DE CASA
SELECT 
EmployeeKey AS ID,
FirstName AS NOME,
HireDate AS DATA_ENTRADA,
EndDate AS DEMISSAO,
DATEDIFF(YEAR, HireDate, EndDate) AS TEMPO_DE_CASA_EM_ANOS
FROM DimEmployee
WHERE EndDate IS NOT NULL

-- FUNCIONARIOS ATIVOS E TEMPO DE CASA
SELECT 
EmployeeKey AS ID,
FirstName AS NOME,
HireDate AS DATA_ENTRADA,
DATEDIFF(YEAR, HireDate, GETDATE()) AS TEMPO_DE_CASA_EM_ANOS
FROM DimEmployee
WHERE EndDate IS NULL
ORDER BY 4 DESC

-- SELECIONANDO OS FUNCIONARIOS E DESCOBRINDO A IDADE DELES
SELECT
EmployeeKey AS ID,
FirstName AS NOME,
BirthDate AS DATA_NASCIMENTO,
DATEDIFF(YEAR, BirthDate, GETDATE()) AS IDADE_FUNCIONARIOS
FROM DimEmployee
WHERE EndDate IS NULL
ORDER BY DATEDIFF(YEAR, BirthDate, GETDATE()) DESC 

-- SELECIONANDO MEU ANIVERSÁRIO
SELECT DATEDIFF(YEAR, '29-06-2001', GETDATE()) AS MINHA_IDADE

-- SELECIONANDO FAIXA ETÁRIA DOS FUNCIONARIOS
SELECT
EmployeeKey AS ID,
FirstName AS NOME,
BirthDate AS DATA_NASCIMENTO,
DATEDIFF(YEAR, BirthDate, GETDATE()) AS IDADE,

-- FAIXA ETARIA
CASE
	WHEN DATEDIFF(YEAR, BirthDate, GETDATE()) BETWEEN 0 AND 20 THEN '0 A 20 ANOS'
	WHEN DATEDIFF(YEAR, BirthDate, GETDATE()) BETWEEN 21 AND 40 THEN '21 A 40 ANOS'
	WHEN DATEDIFF(YEAR, BirthDate, GETDATE()) BETWEEN 40 AND 60 THEN '41 A 60 ANOS'
	WHEN DATEDIFF(YEAR, BirthDate, GETDATE()) BETWEEN 61 AND 80 THEN '61 A 80 ANOS'
	ELSE 'ACIMA DOS 60 ANOS'
END AS FAIXA_ETARIA
FROM DimEmployee
GROUP BY EmployeeKey, FirstName, BirthDate
ORDER BY DATEDIFF(YEAR, BirthDate, GETDATE()) DESC

-- CRIANDO COM SUBQUERY 
SELECT
COUNT(ID) AS QUANTIDADE,
FAIXA_ETARIA

FROM(
	SELECT
EmployeeKey AS ID,
FirstName AS NOME,
BirthDate AS DATA_NASCIMENTO,
DATEDIFF(YEAR, BirthDate, GETDATE()) AS IDADE,

-- FAIXA ETARIA
CASE
	WHEN DATEDIFF(YEAR, BirthDate, GETDATE()) BETWEEN 0 AND 20 THEN '0 A 20 ANOS'
	WHEN DATEDIFF(YEAR, BirthDate, GETDATE()) BETWEEN 21 AND 40 THEN '21 A 40 ANOS'
	WHEN DATEDIFF(YEAR, BirthDate, GETDATE()) BETWEEN 40 AND 60 THEN '41 A 60 ANOS'
	WHEN DATEDIFF(YEAR, BirthDate, GETDATE()) BETWEEN 61 AND 80 THEN '61 A 80 ANOS'
	ELSE 'ACIMA DOS 60 ANOS'
END AS FAIXA_ETARIA
FROM DimEmployee
GROUP BY EmployeeKey, FirstName, BirthDate
) AS TB_FAIXA_ETARIA_FUNC
GROUP BY FAIXA_ETARIA
ORDER BY QUANTIDADE DESC;







-- CRIANDO COM CTE (Common Table Expression)
WITH FaixaEtariaCTE AS (
    SELECT
        EmployeeKey AS ID,
        FirstName AS NOME,
        BirthDate AS DATA_NASCIMENTO,
        DATEDIFF(YEAR, BirthDate, GETDATE()) AS IDADE,
        
        -- FAIXA ETARIA
        CASE
            WHEN DATEDIFF(YEAR, BirthDate, GETDATE()) BETWEEN 0 AND 20 THEN '0 A 20 ANOS'
            WHEN DATEDIFF(YEAR, BirthDate, GETDATE()) BETWEEN 21 AND 40 THEN '21 A 40 ANOS'
            WHEN DATEDIFF(YEAR, BirthDate, GETDATE()) BETWEEN 41 AND 60 THEN '41 A 60 ANOS'
            WHEN DATEDIFF(YEAR, BirthDate, GETDATE()) BETWEEN 61 AND 80 THEN '61 A 80 ANOS'
            ELSE 'ACIMA DOS 80 ANOS'
        END AS FAIXA_ETARIA
    FROM DimEmployee
)

SELECT 
    FAIXA_ETARIA,
    COUNT(*) AS QUANTIDADE
FROM FaixaEtariaCTE
GROUP BY FAIXA_ETARIA
ORDER BY FAIXA_ETARIA;

