SELECT 
SalesOrderNumber AS [ORDEM],
ExtendedAmount AS [VALOR VENDA],
CASE
	WHEN ExtendedAmount < 3000 THEN	'VENDA BAIXA'
	WHEN ExtendedAmount >= 3000 THEN 'VENDA ALTA'
	END AS 'TIPO DE VENDA'

FROM FactResellerSales
-- CONTANDO QUANTAS VENDAS ALTAS E BAIXAS POR ORDEM DE VENDA
SELECT  SalesOrderNumber AS [ORDEM DA VENDA],
	COUNT(CASE WHEN ExtendedAmount < 3000 THEN 1 END) AS [VENDA BAIXA],
	COUNT(CASE WHEN ExtendedAmount >= 3000 THEN 1 END) AS [VENDA ALTA]
FROM FactResellerSales
GROUP BY SalesOrderNumber

-- CONTANDO QUANTAS VENDAS ALTAS E BAIXAS POR ORDEM DE VENDA
SELECT  YEAR (ORDERDATE) AS [ANO],
	COUNT(CASE WHEN ExtendedAmount < 3000 THEN 1 END) AS [VENDA BAIXA],
	COUNT(CASE WHEN ExtendedAmount >= 3000 THEN 1 END) AS [VENDA ALTA]
FROM FactResellerSales
GROUP BY YEAR (ORDERDATE)