-- QUANTIDADE DE VENDAS POR ORDEM DE VENDAS

SELECT
SalesOrderNumber AS [ORDEM DE VENDAS],
 COUNT(CASE WHEN ExtendedAmount < 3000 THEN 1 END) 'VENDA BAIXA',
 COUNT(CASE WHEN ExtendedAmount >= 3000 THEN 1 END) 'VENDA ALTA'

FROM FactResellerSales
GROUP BY SalesOrderNumber