CREATE DATABASE ECOMMERCE default charset utf8 default collate utf8_general_ci,
USE ECOMMERCE,
CREATE TABLE DUPLICATA(
    NOME VARCHAR (60),
    VENCIMENTO DATE,
    VALOR DECIMAL (8, 2),
    CEDENTE VARCHAR(60)
) DEFAULT CHARSET = utf8,
DROP TABLE DUPLICATA,
SELECT
    *
FROM
    DUPLICATA,
INSERT INTO
    DUPLICATA (NOME, VENCIMENTO, VALOR, CEDENTE)
VALUES
(
        "MARIA",
        "2024-03-03",
        20000.00,
        "SANTANDER"
    ),
INSERT INTO
    DUPLICATA (
        NOME,
        VENCIMENTO,
        VALOR,
        CEDENTE
    )
VALUES
    (
        "FELLIPE",
        "2010-08-11",
        2000.00,
        "SANTANDER"
    ),
ALTER TABLE
    DUPLICATA
ADD
    COLUMN NUMERO INT,
ALTER TABLE
    DUPLICATA
ADD
    COLUMN BANCO VARCHAR (60),
    DESC DUPLICATA,
    DROP TABLE DUPLICATA,
    DESC DUPLICATA,