CREATE TABLE CATEGORIA(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL
),
CREATE TABLE PRODUTO(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    QUANTIDADE INT NOT NULL,
    VALOR DECIMAL(10, 2) NOT NULL,
    CATEGORIA_ID INT NOT NULL,
    FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIA (ID)
),
CREATE TABLE VENDEDOR(
    ID_VENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    VENDAS INT NOT NULL,
    PRODUTO_ID INT NOT NULL,
    CATEGORIA_ID INT NOT NULL,
    FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTO (ID),
    FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIA (ID)
),
USE MERCADO,
INSERT INTO
    MERCADO.CATEGORIA(NOME)
VALUES
('ALIMENTOS'),
SELECT
    *
FROM
    MERCADO.CATEGORIA,
INSERT INTO
    MERCADO.PRODUTO(NOME, QUANTIDADE, VALOR, CATEGORIA_ID)
VALUES
('ARROZ', 100, 30.00, 1),
INSERT INTO
    MERCADO.PRODUTO(NOME, QUANTIDADE, VALOR, CATEGORIA_ID)
VALUES
('MACARRÃO', 30, 30.00, 1),
INSERT INTO
    MERCADO.PRODUTO(NOME, QUANTIDADE, VALOR, CATEGORIA_ID)
VALUES
('FEIJÃO', 250, 12.00, 1),
INSERT INTO
    MERCADO.PRODUTO(NOME, QUANTIDADE, VALOR, CATEGORIA_ID)
VALUES
('REQUEIJÃO', 50, 8.00, 1),
SELECT
    *
FROM
    MERCADO.CATEGORIA,
SELECT
    PRODUTO.ID,
    PRODUTO.NOME AS PRODUTO_NOME,
    CATEGORIA.NOME AS CATEGORIA_NOME
FROM
    PRODUTO
    LEFT JOIN CATEGORIA ON PRODUTO.CATEGORIA_ID = CATEGORIA.ID,
ALTER TABLE
    PRODUTO