CREATE DATABASE UNI_SENAC
USE UNI_SENAC

CREATE TABLE ALUNO(
	IDALUNO INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL,
	SEXO CHAR(1) NOT NULL,
	NASCIMENTO DATE NOT NULL,
	[E-MAIL] VARCHAR(30) UNIQUE
)
GO

/*CONSTRAINTS*/
ALTER TABLE ALUNO
ADD CONSTRAINT CK_SEXO CHECK(SEXO IN('M', 'F'))
GO

/*1X1*/
CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY IDENTITY(100, 10),
	BAIRRO VARCHAR(30),
	UF CHAR(2) NOT NULL
	CHECK (UF IN('RJ', 'SP', 'MG')),
	ID_ALUNO INT UNIQUE
)
GO

/*CRIANDO A FK*/
ALTER TABLE ENDERECO ADD CONSTRAINT FK_ENDERECO_ALUNO
FOREIGN KEY(ID_ALUNO) REFERENCES ALUNO(IDALUNO)
GO

/*COMANDO DESC -> SP_COLUMNS (TABLE)*/
SP_COLUMNS ALUNO
GO

SP_HELP ALUNO
GO

/*INSERINDO DADOS*/

INSERT INTO ALUNO
VALUES
('ANDRE', 'M', '1981/12/09', 'ANDRE@IG.COM'),
('ANA', 'F', '1978/03/09', 'ANA@IG.COM'),
('RUI', 'M', '1951/07/09', 'RUI@IG.COM'),
('JOAO', 'M', '2002/11/09', 'JOAO@IG.COM');

SELECT * FROM ALUNO;

INSERT INTO ENDERECO
VALUES
('FLAMENGO', 'RJ', 1),
('MORUMBI', 'SP', 2),
('CENTRO', 'MG', 4),
('CENTRO', 'SP', 3);

/*CRIANDO A TABELA TELEFONES 1XN(MUITOS)*/
CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY IDENTITY,
	TIPO CHAR(3) NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	ID_ALUNO INT,
	CHECK (TIPO IN('RES', 'COM', 'CEL'))
)
GO

INSERT INTO TELEFONE
VALUES
('CEL', '7899889', 1),
('RES', '4325444', 1),
('COM', '4354354', 2),
('CEL', '2344556', 2)
GO

/*CRIANDO A FK*/
ALTER TABLE TELEFONE ADD CONSTRAINT FK_TELEFONE_ALUNO
FOREIGN KEY(ID_ALUNO) REFERENCES ALUNO(IDALUNO)
GO

SELECT * FROM TELEFONE;

/*PEGANDO DATA ATUAL*/
SELECT GETDATE() AS [DATA HOJE]
GO

/*CLAUSULA AMBIGUA*/
SELECT 
[ESTUDANTE].NOME,
[TEL].TIPO,
[TEL].NUMERO,
[END].BAIRRO,
[END].UF
FROM ALUNO [ESTUDANTE]
INNER JOIN TELEFONE [TEL]
ON [ESTUDANTE].IDALUNO = [TEL].ID_ALUNO
INNER JOIN ENDERECO [END]
ON [ESTUDANTE].IDALUNO = [END].ID_ALUNO
GO

SELECT
[ESTUDANTE].NOME,
[TEL].TIPO, [TEL].NUMERO,
[END].BAIRRO, [END].UF
FROM ALUNO [ESTUDANTE] LEFT JOIN TELEFONE [TEL]
ON [ESTUDANTE].IDALUNO = [TEL].ID_ALUNO
INNER JOIN ENDERECO [END]
ON [ESTUDANTE].IDALUNO = [END].ID_ALUNO
GO

/*IFNULL*/
SELECT [ESTUDANTE].NOME,
		ISNULL([TEL].TIPO, 'SEM') AS 'TIPO DE TELEFONE',
		ISNULL([TEL].NUMERO, 'NUMERO') AS 'TELEFONE',
		[END].BAIRRO,
		[END].UF
FROM ALUNO [ESTUDANTE] LEFT JOIN TELEFONE [TEL]
ON [ESTUDANTE].IDALUNO = [TEL].ID_ALUNO
INNER JOIN ENDERECO [END]
ON [ESTUDANTE].IDALUNO = [END].ID_ALUNO
GO

/*DATAS*/
SELECT * FROM ALUNO
GO

SELECT NOME, NASCIMENTO
FROM ALUNO
GO

/*DATEDIFF - CALCULA A DIFERENÇA ENTRE DUAS DATAS*/
SELECT GETDATE() AS [HOJE]
FROM ALUNO

SELECT NOME, DATEDIFF(DAY, NASCIMENTO, GETDATE()) AS [IDADE EM DIAS]
FROM ALUNO
GO

SELECT NOME, (DATEDIFF(DAY, NASCIMENTO, GETDATE())/365) AS [IDADE]
FROM ALUNO
GO

SELECT NOME, (DATEDIFF(DAY, NASCIMENTO, GETDATE())/12) AS [IDADE]
FROM ALUNO
GO

SELECT NOME, DATEDIFF(YEAR, NASCIMENTO, GETDATE()) AS [IDADE]
FROM ALUNO
GO

/*DATENAME*/
SELECT NOME, DATENAME(MONTH, NASCIMENTO) AS [MÊS DE NASCIMENTO]
FROM ALUNO
GO

SELECT NOME, DATENAME(YEAR, NASCIMENTO) AS [ANO DE NASCIMENTO]
FROM ALUNO
GO

SELECT NOME, DATENAME(WEEKDAY, NASCIMENTO) AS [NOME DO DIA DE NASCIMENTO]
FROM ALUNO
GO

/*DATEPART*/
SELECT NOME, DATEPART(MONTH, NASCIMENTO) AS [NÚMERO DO MÊS], DATENAME(MONTH, NASCIMENTO) AS [NOME DO MÊS]
FROM ALUNO
GO

/*DATEADD - ADICIONANDO DATAS EM ANOS, DIAS E MESES..*/
SELECT DATEADD(DAY, 365, GETDATE()) AS [365 DIAS DEPOIS] --DIAS
SELECT DATEADD(YEAR, 10, GETDATE()) AS [10 ANOS DEPOIS] --ANOS

/*CONVERSÃO DE DADOS (CASTING)*/
/*FUNÇÕES DE CONVERSÃO DE DADOS*/

SELECT CAST('1' AS INT) + CAST('1' AS INT)

SELECT NOME,
CAST(DAY(NASCIMENTO) AS VARCHAR) + '/' +
CAST(MONTH(NASCIMENTO) AS VARCHAR) + '/' +
CAST(YEAR(NASCIMENTO) AS VARCHAR)
FROM ALUNO

/*CONTAGEM DEFAULT - INICIA EM 1*/

SELECT NOME, CHARINDEX('A', NOME) AS INDICE
FROM ALUNO
GO

SELECT NOME, CHARINDEX('A', NOME, 2) AS INDICE
FROM ALUNO
GO

/*BULK INSERT IMPORTAÇÃO DE ARQUIVOS*/

CREATE TABLE LANCAMENTO_CONTABIL(
	CONTA INT,
	VALOR INT,
	DEB_CRED CHAR(1)
)
GO

SELECT * FROM LANCAMENTO_CONTABIL
GO

BULK INSERT LANCAMENTO_CONTABIL
FROM 'C:\Users\Felli\Desktop\CONTAS.txt'
WITH(
	FIRSTROW = 2,
	DATAFILETYPE = 'char',
	FIELDTERMINATOR = '\t',
	ROWTERMINATOR = '\n'
)
GO

